# Generated by Django 3.0.6 on 2020-05-20 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200520_1658'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Niv',
            new_name='Niveles',
        ),
    ]
