# Generated by Django 3.0.6 on 2020-05-21 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_rol_id_nivel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rol',
            old_name='id_nivel',
            new_name='nivel',
        ),
    ]
